### ISSUE TITLE
Seen the Crossbeam version of ArcCell?

### ISSUE THREAD

**Issue by sfackler** [Connicpu/arc-cell#1]
Not really a bug, but I wanted to point you towards https://github.com/aturon/crossbeam/blob/master/src/sync/arc_cell.rs, which is a very similar type with a slightly different implementation approach. 😄

**Comment by Connicpu** [comment]
I had not seen that! I had been thinking about how I could implement this without any kind of lock, and that looks pretty good. For my personal use-case I really need the Weak version as well, though ;)
